name: gists_explorer
description: Gists Explorer parser
version: 0.0.1
homepage:

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ^2.5.0

dependencies:
  flutter:
    sdk: flutter

  html: ^0.15.0
  dio: ^4.0.0
  infinite_scroll_pagination: ^3.1.0
  google_fonts: ^2.1.0

dev_dependencies:
  test: ^1.17.10
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/response.html
  fonts:
    - family: Averta
      fonts:
        - asset: assets/fonts/Averta Cyrillic Bold.otf
        - asset: assets/fonts/Averta Cyrillic Regular.otf
          style: normal
        - asset: assets/fonts/Averta Cyrillic SemiBold.otf
